# this file is here to be used to test BaseURL functionality
version: '3'
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8080:8080
  pyroscope:
    build:
      context: ../../..
      dockerfile: Dockerfile
    environment:
      PYROSCOPE_BASE_URL: http://localhost:8080/pyroscope/
    ports:
      - '4040:4040'
    command:
      - 'server'
